//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class CharThumbnail: APIModel {

    public var `extension`: String?

    public var path: String?

    public init(`extension`: String? = nil, path: String? = nil) {
        self.`extension` = `extension`
        self.path = path
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        `extension` = try container.decodeIfPresent("extension")
        path = try container.decodeIfPresent("path")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(`extension`, forKey: "extension")
        try container.encodeIfPresent(path, forKey: "path")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? CharThumbnail else { return false }
      guard self.`extension` == object.`extension` else { return false }
      guard self.path == object.path else { return false }
      return true
    }

    public static func == (lhs: CharThumbnail, rhs: CharThumbnail) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
