//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class CollectionItem: APIModel {

    public var name: String?

    public var resourceURI: String?

    public var type: String?

    public init(name: String? = nil, resourceURI: String? = nil, type: String? = nil) {
        self.name = name
        self.resourceURI = resourceURI
        self.type = type
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        name = try container.decodeIfPresent("name")
        resourceURI = try container.decodeIfPresent("resourceURI")
        type = try container.decodeIfPresent("type")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(name, forKey: "name")
        try container.encodeIfPresent(resourceURI, forKey: "resourceURI")
        try container.encodeIfPresent(type, forKey: "type")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? CollectionItem else { return false }
      guard self.name == object.name else { return false }
      guard self.resourceURI == object.resourceURI else { return false }
      guard self.type == object.type else { return false }
      return true
    }

    public static func == (lhs: CollectionItem, rhs: CollectionItem) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
