//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension MarvelClient.Characters {

    /** Listado de personajes */
    public enum GetCharacterDetail {

        public static let service = APIService<Response>(id: "getCharacterDetail", tag: "Characters", method: "GET", path: "/v1/public/characters/{charId}", hasBody: false)

        public final class Request: APIRequest<Response> {

            public struct Options {

                /** ID del personaje */
                public var charId: String

                public init(charId: String) {
                    self.charId = charId
                }
            }

            public var options: Options

            public init(options: Options) {
                self.options = options
                super.init(service: GetCharacterDetail.service)
            }

            /// convenience initialiser so an Option doesn't have to be created
            public convenience init(charId: String) {
                let options = Options(charId: charId)
                self.init(options: options)
            }

            public override var path: String {
                return super.path.replacingOccurrences(of: "{" + "charId" + "}", with: "\(self.options.charId)")
            }
        }

        public enum Response: APIResponseValue, CustomStringConvertible, CustomDebugStringConvertible {
            public typealias SuccessType = CharactersResponse

            /** 200 OK */
            case status200(CharactersResponse)

            public var success: CharactersResponse? {
                switch self {
                case .status200(let response): return response
                }
            }

            public var response: Any {
                switch self {
                case .status200(let response): return response
                }
            }

            public var statusCode: Int {
                switch self {
                case .status200: return 200
                }
            }

            public var successful: Bool {
                switch self {
                case .status200: return true
                }
            }

            public init(statusCode: Int, data: Data, decoder: ResponseDecoder) throws {
                switch statusCode {
                case 200: self = try .status200(decoder.decode(CharactersResponse.self, from: data))
                default: throw APIClientError.unexpectedStatusCode(statusCode: statusCode, data: data)
                }
            }

            public var description: String {
                return "\(statusCode) \(successful ? "success" : "failure")"
            }

            public var debugDescription: String {
                var string = description
                let responseString = "\(response)"
                if responseString != "()" {
                    string += "\n\(responseString)"
                }
                return string
            }
        }
    }
}
