//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension MarvelClient.Characters {

    /** Listado de personajes */
    public enum GetCharacterList {

        public static let service = APIService<Response>(id: "getCharacterList", tag: "Characters", method: "GET", path: "/v1/public/characters", hasBody: false)

        public final class Request: APIRequest<Response> {

            public struct Options {

                /** límite de resultados */
                public var limit: Int?

                /** obviar los n primeros resultados */
                public var offset: Int?

                /** filtro por nombre */
                public var nameStartsWith: String?

                public init(limit: Int? = nil, offset: Int? = nil, nameStartsWith: String? = nil) {
                    self.limit = limit
                    self.offset = offset
                    self.nameStartsWith = nameStartsWith
                }
            }

            public var options: Options

            public init(options: Options) {
                self.options = options
                super.init(service: GetCharacterList.service)
            }

            /// convenience initialiser so an Option doesn't have to be created
            public convenience init(limit: Int? = nil, offset: Int? = nil, nameStartsWith: String? = nil) {
                let options = Options(limit: limit, offset: offset, nameStartsWith: nameStartsWith)
                self.init(options: options)
            }

            public override var queryParameters: [String: Any] {
                var params: [String: Any] = [:]
                if let limit = options.limit {
                  params["limit"] = limit
                }
                if let offset = options.offset {
                  params["offset"] = offset
                }
                if let nameStartsWith = options.nameStartsWith {
                  params["nameStartsWith"] = nameStartsWith
                }
                return params
            }
        }

        public enum Response: APIResponseValue, CustomStringConvertible, CustomDebugStringConvertible {
            public typealias SuccessType = CharactersResponse

            /** 200 OK */
            case status200(CharactersResponse)

            public var success: CharactersResponse? {
                switch self {
                case .status200(let response): return response
                }
            }

            public var response: Any {
                switch self {
                case .status200(let response): return response
                }
            }

            public var statusCode: Int {
                switch self {
                case .status200: return 200
                }
            }

            public var successful: Bool {
                switch self {
                case .status200: return true
                }
            }

            public init(statusCode: Int, data: Data, decoder: ResponseDecoder) throws {
                switch statusCode {
                case 200: self = try .status200(decoder.decode(CharactersResponse.self, from: data))
                default: throw APIClientError.unexpectedStatusCode(statusCode: statusCode, data: data)
                }
            }

            public var description: String {
                return "\(statusCode) \(successful ? "success" : "failure")"
            }

            public var debugDescription: String {
                var string = description
                let responseString = "\(response)"
                if responseString != "()" {
                    string += "\n\(responseString)"
                }
                return string
            }
        }
    }
}
