//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** API de Marvel */
public struct MarvelClient {

    /// Whether to discard any errors when decoding optional properties
    public static var safeOptionalDecoding = false

    /// Whether to remove invalid elements instead of throwing when decoding arrays
    public static var safeArrayDecoding = false

    /// Used to encode Dates when uses as string params
    public static var dateEncodingFormatter = DateFormatter(formatString: "yyyy-MM-dd'T'HH:mm:ssZZZZZ")

    public static let version = "1.0.0"

    public enum Characters {}

    public enum Server {

        public static let main = "https://gateway.marvel.com:443"
    }
}
